name: Componly

on:
  push:
    branches:
      - debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18
          
    - name: Install dependencies
      id: install-dependencies
      run: |
        echo  -e "\n@componly:registry=https://npm.pkg.github.com/" >> .npmrc
        echo //npm.pkg.github.com/:_authToken=${{secrets.COMPONLY_NPM_AUTH_TOKEN}} >> .npmrc
        yarn install 

    - name: scan
      id: componly-scan
      run: yarn scan 

    - name: Post scan.json
      id: post-scan
      uses: actions/github-script@v5
      with:
        script: |
          const  FormData = require ("form-data");
          const  { createReadStream } = require ("fs");
          const  axios = require ("axios");
          const fetch=require("node-fetch")
          async function postScan() {
            const rawUserResponse = await fetch(
              "https://backend-production-e808.up.railway.app/auth/login",
              {
                method: "POST",
                headers: {
                  "Content-Type": "application/json",
                },
                body: JSON.stringify({
                  email: ${{secrets.COMPONLY_USERNAME}},
                  password: ${{secrets.COMPONLY_PASSWORD}},
                }),
              }
            );
            const { response: userInfo } = await rawUserResponse.json();

            const rawProjectInfo = await fetch(
              "https://backend-production-e808.up.railway.app/companies/projects?page=1&pageSize=1&with-cli=true&with-sourceCodes=true",
              {
                method: "GET",
                headers: {
                  "Content-Type": "application/json",
                  Authorization: `Bearer ${userInfo.token}`,
                },
              }
            );
            const { projects } = await rawProjectInfo.json();
            const [project] = projects;
            const { id: cliId, password } = project.cli;
            const [sourceCode] = project.sourceCodes;

            const projectLoginResponse = await fetch(
              "https://backend-production-e808.up.railway.app/auth/login/cli",
              {
                method: "POST",
                headers: {
                  "Content-Type": "application/json",
                },
                body: JSON.stringify({
                  cliId,
                  password,
                }),
              }
            );
            const { token } = await projectLoginResponse.json();
            const formData = new FormData();
            const fileStream = createReadStream("./.componly/scan.json");
            formData.append("file", fileStream);

            const res = await axios.post(
              `https://backend-production-e808.up.railway.app/scans/upload/${sourceCode.id}`,
              formData,
              {
                headers: {
                  Authorization: `Bearer ${token}`,
                  "Content-Type": "multipart/form-data",
                },
              }
            );

            console.log(res);
          }

          postScan();
