name: Componly

on:
  push:
    branches:
      - nmohan/#1046-support-for-github-actions-part-2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18
          
    - name: Install dependencies
      id: install-dependencies
      run: |
        echo  -e "\n@componly:registry=https://npm.pkg.github.com/" >>.npmrc
        echo //npm.pkg.github.com/:_authToken=${{secrets.COMPONLY_NPM_AUTH_TOKEN}} >>.npmrc
        cat .npmrc
        yarn install 

    - name: scan
      id: componly-scan
      run: yarn scan 